### ISSUE TITLE
Be able to suppress warnings

### ISSUE THREAD

**Issue by damianh** [mihasic/DateTimeNowAnalyzer#2]
So at some _point_ in code you'll need access `DateTime.UtcNow`, at least in the application root.

It would be nice to be able to suppress the warning. Something like this (though I don't know if this is the correct approach):

```
#pragma warning disable DateTimeNowAnalyzer
_getUtcNow = () => DateTimeOffset.UtcNow;
#pragma warning enable DateTimeNowAnalyzer
```

**Comment by mihasic** [comment]
I assume R# is overriding VS menu (default). The error can be disabled with comment, I'll check later on the format.

**Comment by mihasic** [comment]
![screen](https://cloud.githubusercontent.com/assets/266282/12216672/f7323c12-b6e9-11e5-887a-4482dbab49cc.gif)
