### ISSUE TITLE
What is meaning of this extension?

### ISSUE THREAD

**Issue by tiksn** [mihasic/DateTimeNowAnalyzer#3]
Please add readme.
why and how should we use it?
Can you also add analyzer for replacing "DateTime" with "DateTimeOffset"?

**Comment by mihasic** [comment]
Will add readme when have more spare time, thought that extension is fairly simple and self-descriptive.

> why and how should we use it?

Extension gives warnings on places with potential side effects related to DateTime. Developed as a result of multiple discussions and big refactoring within the company I work.
DateTime.Now and similar can lead to some side effects in the code. Best practice is to have an abstraction somewhere on the top level. So in tests it would be possible to have a stub (or use RX Scheduler) and have predictable results.

> Can you also add analyzer for replacing "DateTime" with "DateTimeOffset"?

I would, when I'll be able to make VS2017 work on my machine (was going to port it). But, in general, it's not really the goal. DateTimeOffset.[Utc]Now - still brings a static mutable state to the application, which leads to side effects.

**Comment by mihasic** [comment]
found some similar discussion: https://github.com/DotNetAnalyzers/Proposals/issues/9

**Comment by tiksn** [comment]
Thank you for your response. And thanks for tool.
